# Generated by Django 2.2.5 on 2020-08-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20191204_0703'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityCounter',
            fields=[
                ('priority', models.IntegerField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
