# Generated by Django 2.2.5 on 2020-08-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_prioritycounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prioritycounter',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
