# Generated by Django 2.2.5 on 2020-08-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20200804_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prioritycounter',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Высокий приоритет'), (2, 'Средний приоритет'), (3, 'Низкий приоритет')], default=2, primary_key=True, serialize=False, verbose_name='Приоритет'),
        ),
    ]
